---
services:
  jenkins:
    image: 'jenkins/jenkins:lts-alpine'
    ports:
      - 11037:8080
      - 50000:50000
    volumes:
      - ./volumes/jenkins_home:/var/jenkins_home
  ruby:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: 'ruby seed_script.rb'
    volumes:
      - "${PWD}/jenkins_api_caller_spec.rb:/jenkins_api_caller_spec.rb"
      - "${PWD}/jenkins_api_caller.rb:/jenkins_api_caller.rb"
      - "${PWD}/seed_script.rb:/seed_script.rb"
version: '3.3'
